name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:next-jammy

    steps:
    - uses: actions/checkout@v3
    - name: yarn lint and test
      run: |
        yarn install
        yarn lint
        yarn test
      env:
        CI: true
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: HOME=/root yarn playwright test
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Build static page for deployment
      if: github.ref_name == 'main'
      run: yarn predeploy
    - name: Deploy to GH Pages 🚀
      if: github.ref_name == 'main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
